version: '3.8'

services:
  database:
    container_name: 'database'
    image: 'postgres:latest'
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
  
  # TODO: wait-for
  server:
    container_name: 'server'
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - database
    env_file:
      - .env

volumes:
  pgdata-prod: {}