version: '3.8'

# Just a postgres database for development
services:
  devdatabase:
    container_name: 'dev_database'
    image: 'postgres:latest'
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.local
    volumes:
      - ./pgdata-dev:/var/lib/postgresql/data
