version: '3.8'

services:
  database:
    container_name: 'database'
    image: 'postgres:latest'
    restart: always
    env_file:
      - ./server/.env
    volumes:
      - pgdata-prod:/var/lib/postgresql/data
  
  server:
    container_name: 'server'
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - database
    env_file:
      - ./server/.env

  client:
    container_name: 'client'
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - server

volumes:
  pgdata-prod: {}